<?php
$typeArr[1] = '关于我们';
$typeArr[2] = '公司简介';
$typeArr[3] = '企业文化';
$typeArr[5] = '产品展示';
$typeArr[6] = '生态红系列';
$typeArr[7] = '健康红系列';
$typeArr[8] = '礼品盒系列';
$typeArr[9] = '加工类系列';
$typeArr[10] = '新闻中心';
$typeArr[11] = '集团新闻';
$typeArr[12] = '企业新闻';
$typeArr[13] = '行业新闻';
$typeArr[14] = '加盟代理';
$typeArr[15] = '加盟代理';
$typeArr[16] = '网络销售';
$typeArr[17] = '网络销售';
$typeArr[18] = '在线留言';
$typeArr[19] = '在线留言';
$typeArr[20] = '联系方式';
$typeArr[21] = '联系方式';
?>