
<field:liuyanbiaoti itemname="留言标题" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:liuyanbiaoti>

<field:biaotineirong itemname="留言内容" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:biaotineirong>

<field:chengwei itemname="您的称谓" autofield="1" type="select" isnull="true" default="先生,女士"  maxlength="250" page="">
</field:chengwei>

<field:dianziyouxiang itemname="电子邮件" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dianziyouxiang>

<field:nidexingming itemname="您的姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:nidexingming>

<field:lianxidianhua itemname="联系电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:lianxidianhua>
