<?php
$z[0]=Array("field","",294,313);
$z[0][4]['name']="title";
$z[1]=Array("global","",314,340);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1036,1071);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","\r\n		  <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n		  ",1755,1884);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[4]=Array("global","",1967,1991);
$z[4][4]['name']="cfg_dizhi";
$z[5]=Array("global","",2016,2042);
$z[5][4]['name']="cfg_dianhua";
$z[6]=Array("global","",2067,2094);
$z[6][4]['name']="cfg_quanzhen";
$z[7]=Array("global","",2119,2146);
$z[7][4]['name']="cfg_youxiang";
$z[8]=Array("field","",2259,2288);
$z[8][4]['name']="typename";
$z[9]=Array("field","",2316,2345);
$z[9][4]['name']="position";
$z[10]=Array("field","",2436,2455);
$z[10][4]['name']="title";
$z[11]=Array("productimagelist","\r\n		<div class=\"img\"> <img alt=\"\" src=\"[field:imgsrc/]\"> </div>\r\n		",2469,2583);
$z[12]=Array("prenext","",3407,3432);
$z[12][4]['get']="pre";
$z[13]=Array("prenext","",3436,3462);
$z[13][4]['get']="next";
$z[14]=Array("include","",3578,3615);
$z[14][4]['filename']="footer.htm";

?>