<?php
$z[0]=Array("global","",294,320);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",966,1001);
$z[1][4]['filename']="head.htm";
$z[2]=Array("arclist","\r\n		  <li><span class=\"left\">·<a href=\"[field:arcurl /]\">[field:title /]</a></span><span class=\"right\">2013-06-28</span></li>	\r\n		 ",2217,2430);
$z[2][4]['row']="3";
$z[2][4]['typeid']="10";
$z[2][4]['titlelen']="30";
$z[2][4]['orderby']="pubdate";
$z[3]=Array("arclist","\r\n		  <li>\r\n            <dt><a href=\"[field:arcurl /]\"><img src=\"[field:picname/]\"></a></dt>\r\n            <dd><a href=\"[field:arcurl /]\">[field:title /]</a></dd>\r\n          </li>\r\n		   ",3610,3876);
$z[3][4]['row']="10";
$z[3][4]['typeid']="5";
$z[3][4]['titlelen']="20";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("include","",3954,3991);
$z[4][4]['filename']="footer.htm";

?>