<?php
$z[0]=Array("field","",294,313);
$z[0][4]['name']="title";
$z[1]=Array("global","",314,340);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1066,1101);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","\r\n		  <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n		  ",1787,1916);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[4]=Array("global","",1999,2023);
$z[4][4]['name']="cfg_dizhi";
$z[5]=Array("global","",2048,2074);
$z[5][4]['name']="cfg_dianhua";
$z[6]=Array("global","",2099,2126);
$z[6][4]['name']="cfg_quanzhen";
$z[7]=Array("global","",2151,2178);
$z[7][4]['name']="cfg_youxiang";
$z[8]=Array("field","",2296,2325);
$z[8][4]['name']="typename";
$z[9]=Array("field","",2353,2382);
$z[9][4]['name']="position";
$z[10]=Array("list","\r\n		  <li><span class=\"left\"><a href=\"[field:arcurl/]\">[field:title/]</a></span><span class=\"right\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span></li>\r\n		  ",2473,2688);
$z[10][4]['pagesize']="8";
$z[10][4]['infolen']="150";
$z[11]=Array("pagelist","",2728,2787);
$z[11][4]['istitem']="index,pre,next,end,";
$z[11][4]['listsize']="5";
$z[12]=Array("include","",2893,2930);
$z[12][4]['filename']="footer.htm";

?>