<?php
$z[0]=Array("field","",294,313);
$z[0][4]['name']="title";
$z[1]=Array("global","",314,340);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1059,1094);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","\r\n		  <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n		  ",1778,1907);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[4]=Array("global","",1990,2014);
$z[4][4]['name']="cfg_dizhi";
$z[5]=Array("global","",2039,2065);
$z[5][4]['name']="cfg_dianhua";
$z[6]=Array("global","",2090,2117);
$z[6][4]['name']="cfg_quanzhen";
$z[7]=Array("global","",2142,2169);
$z[7][4]['name']="cfg_youxiang";
$z[8]=Array("field","",2281,2310);
$z[8][4]['name']="typename";
$z[9]=Array("field","",2338,2367);
$z[9][4]['name']="position";
$z[10]=Array("list","\r\n		<dl>\r\n          <dt><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\"></a></dt>\r\n          <dd><a href=\"[field:arcurl/]\">[field:title/]</a></dd>\r\n        </dl>\r\n		",2443,2651);
$z[10][4]['pagesize']="12";
$z[11]=Array("pagelist","",2677,2736);
$z[11][4]['istitem']="index,pre,next,end,";
$z[11][4]['listsize']="5";
$z[12]=Array("include","",2842,2879);
$z[12][4]['filename']="footer.htm";

?>